org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.warning.mode=fail
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US -Duser.timezone=UTC
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
